-- premake5.lua

workspace "alica"
   configurations { "Debug", "Release" }

project "dynamic_role_assignment"
   kind "StaticLib"
   language "C++"
   cppdialect "C++14"
   targetdir "bin/%{cfg.buildcfg}"

   libdirs { 
      os.findlib("uuid")
     }

   links { 
      "uuid" 
   }

   includedirs {
      "include", 
      "../alica/alica_engine/include",
      "../alica/alica_common_config/include" ,
      "../essentials/id_manager/include" , 
      "../essentials/system_config/include" , 
      "../essentials/fsystem/include" ,

       --"../alica/alica_solver_interface/include" ,
      --"../alica/alica_simple_solver/include" ,
      -- "../alica/alica_dummy_proxy/include" ,
       --"../alica-supplementary/alica_capnzero_proxy/include" ,
       --"../essentials/event_handling/include" ,
       --"../capnzero/capnzero/include",
      
      --"../capnproto/c++/src",
      --"../libzmq/include",
      --"../yaml-cpp/include" ,
      
      --"../googletest/googletest/include",
      --"alica_tests/include" ,
      --"alica_tests/autogenerated/include" ,
   }
   
   linkoptions { 
      "../alica/alica_engine/bin/Debug/libalica_engine.a", 
      "../alica/alica_common_config/bin/Debug/libalica_common_config.a", 
      "../essentials/id_manager/bin/Debug/libid_manager.a",
      "../essentials/system_config/bin/Debug/libsystem_config.a",
      "../essentials/fsystem/bin/Debug/libfsystem.a",

      
      --"../alica/alica_solver_interface/bin/Debug/libalica_solver_interface.a",
      --"../essentials/event_handling/bin/Debug/libevent_handling.a",
      -- "../alica-supplementary/alica_capnzero_proxy/bin/Debug/libalica_capnzero_proxy.a",
      -- "../capnzero/capnzero/bin/Debug/libcapnzero.a",
      -- "../capnzero/id_capnzero/bin/Debug/libid_capnzero.a",

      -- "../libzmq/src/.libs/libzmq.a",
      -- "../capnproto/c++/.libs/libcapnp.a",
      -- "../capnproto/c++/.libs/libkj.a",
      -- "../yaml-cpp/build/libyaml-cpp.a",
      -- "uuid" 
   }

   files {      
      "include/**.h", 
      "src/**.cpp",  
   }
   
   excludes {
      "src/test/**",
   }

   filter "configurations:Debug"
      defines { "DEBUG" }
      symbols "On"

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"
   


