# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  dynamic_role_assignment_config = debug

else ifeq ($(config),release)
  dynamic_role_assignment_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := dynamic_role_assignment

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

dynamic_role_assignment:
ifneq (,$(dynamic_role_assignment_config))
	@echo "==== Building dynamic_role_assignment ($(dynamic_role_assignment_config)) ===="
	@${MAKE} --no-print-directory -C . -f dynamic_role_assignment.make config=$(dynamic_role_assignment_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f dynamic_role_assignment.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   dynamic_role_assignment"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"